2016-01-29T15:37:53+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:37:53+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:37:53+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:37:53+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:21+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:21+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:21+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:21+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:21+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:21+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:21+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:21+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:29+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:37+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:37+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:37+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:37+00:00 EMERG (0):   1 MB | Pimcore\Config::getSystemConfig() [40]: Cannot find system configuration, should be located at: /var/www/html/pimcore/nyt/website/var/config/system.xml
2016-01-29T15:38:37+00:00 DEBUG (7):   2 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 39
2016-01-29T15:38:45+00:00 DEBUG (7):   2 MB | Pimcore\Resource\Wrapper->closeConnectionResource() [135]: Zend_Db_Adapter_Mysqli: closing MySQL-Server connection with ID: 39
2016-01-29T16:38:45+01:00 DEBUG (7):   2 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 40
2016-01-29T16:38:47+01:00 DEBUG (7):   2 MB | Pimcore\Model\Cache::load() [289]: Key pimcore_system_resource_columns_users doesn't exist in cache
2016-01-29T16:38:47+01:00 ERR (3):   2 MB | Pimcore\Model\Cache::storeToCache() [426]: Failed to add entry pimcore_system_resource_columns_users to the cache, item-size was 370 B
2016-01-29T16:38:47+01:00 DEBUG (7):   2 MB | Pimcore\Model\Cache::storeToCache() [429]: Added pimcore_system_resource_columns_users to cache
2016-01-29T16:38:47+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:38:47+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 41
2016-01-29T16:38:48+01:00 ERR (3):   9 MB | Pimcore\Controller\Action\Admin->init() [127]: Prevented access to /admin/ because there is no user in the session!
2016-01-29T16:38:48+01:00 ERR (3):   9 MB | Array
(
    [server] => Array
        (
            [REDIRECT_STATUS] => 200
            [HTTP_HOST] => nyt.local
            [HTTP_USER_AGENT] => Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0
            [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
            [HTTP_ACCEPT_LANGUAGE] => en-US,en;q=0.5
            [HTTP_ACCEPT_ENCODING] => 
            [HTTP_REFERER] => http://nyt.local/install/
            [HTTP_COOKIE] => ZDEDebuggerPresent=php,phtml,php3; ZS6SESSID=hlgmrkjpi9af2cvg3r973243i4; ZSDEVBAR=%7B%7D
            [HTTP_CONNECTION] => keep-alive
            [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
            [SERVER_SIGNATURE] => <address>Apache/2.4.7 (Ubuntu) Server at nyt.local Port 80</address>

            [SERVER_SOFTWARE] => Apache/2.4.7 (Ubuntu)
            [SERVER_NAME] => nyt.local
            [SERVER_ADDR] => 127.0.0.1
            [SERVER_PORT] => 80
            [REMOTE_ADDR] => 127.0.0.1
            [DOCUMENT_ROOT] => /var/www/html/pimcore/nyt
            [REQUEST_SCHEME] => http
            [CONTEXT_PREFIX] => 
            [CONTEXT_DOCUMENT_ROOT] => /var/www/html/pimcore/nyt
            [SERVER_ADMIN] => [no address given]
            [SCRIPT_FILENAME] => /var/www/html/pimcore/nyt/index.php
            [REMOTE_PORT] => 49303
            [REDIRECT_URL] => /admin/
            [GATEWAY_INTERFACE] => CGI/1.1
            [SERVER_PROTOCOL] => HTTP/1.1
            [REQUEST_METHOD] => GET
            [QUERY_STRING] => 
            [REQUEST_URI] => /admin/
            [SCRIPT_NAME] => /index.php
            [PHP_SELF] => /index.php
            [REQUEST_TIME_FLOAT] => 1454081927.885
            [REQUEST_TIME] => 1454081927
            [TMPDIR] => /var/www/html/pimcore/nyt/website/var/cache
            [TEMP] => /var/www/html/pimcore/nyt/website/var/cache
            [TMP] => /var/www/html/pimcore/nyt/website/var/cache
            [windir] => /var/www/html/pimcore/nyt/website/var/cache
            [SystemRoot] => /var/www/html/pimcore/nyt/website/var/cache
        )

    [get] => Array
        (
        )

    [post] => Array
        (
        )

    [session] => 
    [cookie] => Array
        (
            [ZDEDebuggerPresent] => php,phtml,php3
            [ZS6SESSID] => hlgmrkjpi9af2cvg3r973243i4
            [ZSDEVBAR] => {}
        )

)

2016-01-29T16:38:48+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:38:48+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 42
2016-01-29T16:39:30+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:39:30+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 43
2016-01-29T16:39:31+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 44
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 45
2016-01-29T16:39:31+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 46
2016-01-29T16:39:31+01:00 INFO (6):   9 MB | Pimcore\Model\Schedule\Manager\Factory::getManager() [47]: Using Schedule\Manager\Procedural as maintenance manager
2016-01-29T16:39:31+01:00 WARN (4):   9 MB | Pimcore\Video\Adapter\Ffmpeg->isAvailable() [50]: [Exception] with message: No ffmpeg executable found, please configure the correct path in the system settings
In file: /var/www/html/pimcore/nyt/pimcore/lib/Pimcore/Video/Adapter/Ffmpeg.php on line 84
#0 /var/www/html/pimcore/nyt/pimcore/lib/Pimcore/Video/Adapter/Ffmpeg.php(44): Pimcore\Video\Adapter\Ffmpeg::getFfmpegCli()
#1 /var/www/html/pimcore/nyt/pimcore/lib/Pimcore/Video.php(69): Pimcore\Video\Adapter\Ffmpeg->isAvailable()
#2 /var/www/html/pimcore/nyt/pimcore/lib/Pimcore/Video.php(51): Pimcore\Video::getDefaultAdapter()
#3 /var/www/html/pimcore/nyt/pimcore/modules/admin/views/scripts/index/index.php(522): Pimcore\Video::isAvailable()
#4 /var/www/html/pimcore/nyt/pimcore/lib/Zend/View.php(157): include('/var/www/html/p...')
#5 /var/www/html/pimcore/nyt/pimcore/lib/Zend/View/Abstract.php(888): Zend_View->_run('/var/www/html/p...')
#6 /var/www/html/pimcore/nyt/pimcore/lib/Zend/Controller/Action/Helper/ViewRenderer.php(912): Zend_View_Abstract->render('index/index.php')
#7 /var/www/html/pimcore/nyt/pimcore/lib/Zend/Controller/Action/Helper/ViewRenderer.php(933): Zend_Controller_Action_Helper_ViewRenderer->renderScript('index/index.php', NULL)
#8 /var/www/html/pimcore/nyt/pimcore/lib/Zend/Controller/Action/Helper/ViewRenderer.php(972): Zend_Controller_Action_Helper_ViewRenderer->render()
#9 /var/www/html/pimcore/nyt/pimcore/lib/Pimcore/Controller/Action/Helper/ViewRenderer.php(42): Zend_Controller_Action_Helper_ViewRenderer->postDispatch()
#10 /var/www/html/pimcore/nyt/pimcore/lib/Zend/Controller/Action/HelperBroker.php(277): Pimcore\Controller\Action\Helper\ViewRenderer->postDispatch()
#11 /var/www/html/pimcore/nyt/pimcore/lib/Zend/Controller/Action.php(527): Zend_Controller_Action_HelperBroker->notifyPostDispatch()
#12 /var/www/html/pimcore/nyt/pimcore/lib/Zend/Controller/Dispatcher/Standard.php(308): Zend_Controller_Action->dispatch('indexAction')
#13 /var/www/html/pimcore/nyt/pimcore/lib/Zend/Controller/Front.php(954): Zend_Controller_Dispatcher_Standard->dispatch(Object(Zend_Controller_Request_Http), Object(Zend_Controller_Response_Http))
#14 /var/www/html/pimcore/nyt/pimcore/lib/Pimcore.php(285): Zend_Controller_Front->dispatch()
#15 /var/www/html/pimcore/nyt/index.php(18): Pimcore::run()
#16 {main}
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 48
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 47
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 49
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 50
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:39:31+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 51
2016-01-29T16:39:32+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 52
2016-01-29T16:39:32+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:39:32+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 53
2016-01-29T16:39:32+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 54
2016-01-29T16:39:32+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::load() [289]: Key pimcore_translations_admin_data doesn't exist in cache
2016-01-29T16:39:32+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 55
2016-01-29T16:39:32+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 56
2016-01-29T16:39:32+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::storeToCache() [429]: Added pimcore_translations_admin_data to cache
2016-01-29T16:39:32+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 57
2016-01-29T16:39:32+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::load() [289]: Key pimcore_system_supported_locales_en doesn't exist in cache
2016-01-29T16:39:32+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 58
2016-01-29T16:40:53+01:00 DEBUG (7):  10 MB | Pimcore\Model\Cache::storeToCache() [429]: Added pimcore_system_supported_locales_en to cache
2016-01-29T16:40:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 59
2016-01-29T16:40:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 60
2016-01-29T16:40:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 62
2016-01-29T16:40:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 61
2016-01-29T16:40:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 63
2016-01-29T16:40:54+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:54+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 64
2016-01-29T16:40:54+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 65
2016-01-29T16:40:54+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:54+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 66
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 67
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 68
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 69
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::load() [289]: Key pimcore_document_1 doesn't exist in cache
2016-01-29T16:40:55+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 70
2016-01-29T16:40:55+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 71
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::load() [287]: Successfully got data for key pimcore_system_supported_locales_en from cache
2016-01-29T16:40:55+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:55+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 72
2016-01-29T16:40:55+01:00 DEBUG (7):  10 MB | Pimcore\Model\Cache::storeToCache() [393]: prepared Pimcore\Model\Document\Page 1 for data cache with tags: document_1
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 73
2016-01-29T16:40:55+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:55+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 74
2016-01-29T16:40:55+01:00 DEBUG (7):  10 MB | Pimcore\Model\Cache::storeToCache() [429]: Added pimcore_document_1 to cache
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 75
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::load() [289]: Key pimcore_asset_1 doesn't exist in cache
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::storeToCache() [393]: prepared Pimcore\Model\Asset\Folder 1 for data cache with tags: asset_1
2016-01-29T16:40:55+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:55+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 76
2016-01-29T16:40:55+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 77
2016-01-29T16:40:56+01:00 DEBUG (7):  10 MB | Pimcore\Model\Cache::storeToCache() [429]: Added pimcore_asset_1 to cache
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 78
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::load() [289]: Key pimcore_object_1 doesn't exist in cache
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::storeToCache() [393]: prepared Pimcore\Model\Object\Folder 1 for data cache with tags: object_1
2016-01-29T16:40:56+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:56+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 79
2016-01-29T16:40:56+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::storeToCache() [429]: Added pimcore_object_1 to cache
2016-01-29T16:40:56+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 80
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 81
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::load() [287]: Successfully got data for key pimcore_document_1 from cache
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 82
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::load() [287]: Successfully got data for key pimcore_asset_1 from cache
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 83
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 84
2016-01-29T16:40:56+01:00 DEBUG (7):   9 MB | Pimcore\Model\Cache::load() [287]: Successfully got data for key pimcore_object_1 from cache
2016-01-29T16:41:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:41:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 85
2016-01-29T16:41:53+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 86
2016-01-29T16:42:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:42:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 87
2016-01-29T16:42:53+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 88
2016-01-29T16:43:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:43:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 89
2016-01-29T16:43:53+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 90
2016-01-29T16:44:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:44:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 91
2016-01-29T16:44:53+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 92
2016-01-29T16:45:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:45:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 93
2016-01-29T16:45:53+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 94
2016-01-29T16:46:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:46:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 95
2016-01-29T16:46:53+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 96
2016-01-29T16:47:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:47:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 97
2016-01-29T16:47:53+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 98
2016-01-29T16:48:53+01:00 DEBUG (7):   1 MB | Pimcore\Cache\Backend\MysqlTable->getDb() [46]: Initialize dedicated MySQL connection for the cache adapter
2016-01-29T16:48:53+01:00 DEBUG (7):   1 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 99
2016-01-29T16:48:53+01:00 DEBUG (7):   9 MB | Pimcore\Resource\Mysql::getConnection() [107]: Zend_Db_Adapter_Mysqli: Successfully established connection to MySQL-Server, Process-ID: 100
